// Generated by auto imports
export {}
declare global {
  const useRuntimeConfig: (event?: import('h3').H3Event) => import('nuxt/schema').RuntimeConfig
  const useAppConfig: () => import('nuxt/schema').AppConfig
  const defineAppConfig: <C extends import('nuxt/schema').AppConfigInput>(config: C) => C
  const createError: typeof import('h3')['createError']
  const setResponseStatus: typeof import('h3')['setResponseStatus']
  const buildCandidatePath: typeof import('../../shared/utils/routes').buildCandidatePath
  const buildCategoryPath: typeof import('../../shared/utils/routes').buildCategoryPath
  const buildMythPath: typeof import('../../shared/utils/routes').buildMythPath
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Verdict, Candidate, Category, MythSource, Myth } from '../../shared/types/content'
  import('../../shared/types/content')
}